name: Lint Shell Scripts

on: [push, pull_request]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ShellCheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: run ShellCheck
      run: |
        find . -name "*.sh" -exce shellcheck {} \;

